# Generated by Django 4.2.7 on 2023-11-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150)),
                ('descricao_produto', models.CharField(max_length=254)),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros_produtos.tbl_tipo_materiais')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros_produtos.tbl_tipo_produtos')),
            ],
        ),
    ]
