# Generated by Django 4.2.7 on 2023-11-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tipo_materiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_tipo_produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_produto', models.CharField(max_length=100)),
            ],
        ),
    ]
